### ISSUE TITLE
Epub/Mobi Formatting

### ISSUE THREAD

**Issue by Mondyboy** [kolyvan/kybook#63] opened 2018-10-02 04:30 UTC
I’ve noted some fortmatting issues which I’ve documented below.  Basically the reader, in some cases, doesn’t put a section break between the cover and the opening text (image 1)

Image 2 shows the next page of that book where the introductory pages - praising the novel - aren’t formatted properly.

And then in Image 3 the book starts without a break.

Image 4 shows how that looks in the original .mobi file.  (I ran the book through Calibre to remove DRM).

It isn’t just a mobi issue the problem also exists with epubs - as an example image 5 shows a lack of spacing between the title of a chapter and the text.  When I ran the same through another reader there was appropriate spacing (image 6).

Yes, I’ve played with the formatting preferences, but when I went back to default these issues existed. https://uploads.disquscdn.com/images/1217f63f090c578dce81ea5154f78aa7c286a10b93a72b45619586fd5053b3d6.jpg https://uploads.disquscdn.com/images/56ab57443f66070e54b02b75cbd84b5da3b1b3ce69658d41bb27ba461d4f6dbf.jpg https://uploads.disquscdn.com/images/5168768d86d79545d43045518115ce7a53e5ae55c56192fd4340f6133ae44162.jpg https://uploads.disquscdn.com/images/d549ffddc389123c6438d7a5cde0df495c8c4e17992336f59f20eaca1cb4326d.png https://uploads.disquscdn.com/images/2cffb55cf00c17e266c4fa5986eb078590bef91f65e965c6d7f1e46e422b93bf.jpg https://uploads.disquscdn.com/images/cf5de783e81e2b19dca8d681c0df624adbdb23b68aae93f5b53c5a12efa38698.jpg

**Comment by kolyvan** [comment] 2018-10-02 04:33
Thank you very much for reporting.
Could you please also attach the link to the epub or mobi with this problem?

**Comment by Mondyboy** [comment] 2018-10-02 04:39
How do I do that?  When I tried to attach it said it didn’t support the file type.

**Comment by kolyvan** [comment] 2018-10-02 04:43
The easiest solution - first, upload an ebook to any cloud storage, then share a file and post here a link. Or just send mail to me at support@kybook-reader.com with an attached ebook.

**Comment by kolyvan** [comment] 2018-10-02 04:44
For sending email with an ebook, open KyBook, long-press on the ebook, select `Share` menu item, then select `Mail`

**Comment by Mondyboy** [comment] 2018-10-02 04:47
I’ve sent via email.  Hopefully you have them.

**Comment by kolyvan** [comment] 2018-10-02 04:50
Yes, I had received ebooks. 
Thank you very much once more for your help.

Unfortunately at the moment I can't say exactly when this issue will be fixed.
Many things need to be checked.

**Comment by Mondyboy** [comment] 2018-10-02 04:52
No problems.

**Comment by Mondyboy** [comment] 2018-10-02 04:52
Oops I closed it by accident.

**Comment by kolyvan** [comment] 2018-10-02 05:14
> Basically the reader, in some cases, doesn’t put a section break between the cover and the opening text (image 1)

Sorry but unable to see a problem, there is a line break.

> Image 2 shows the next page of that book where the introductory pages - praising the novel - aren’t formatted properly.
> And then in Image 3 the book starts without a break.

Sorry, unable reproduce.
Maybe do you override the default app settings?
Bellow my screenshots.

![kybook-mobi-1](https://user-images.githubusercontent.com/791320/46330226-2d570e80-c655-11e8-8dea-fc2aeae0ea2c.png)

![kybook-mobi-2](https://user-images.githubusercontent.com/791320/46330260-4cee3700-c655-11e8-8a0d-9cf2d71c61ed.png)

> Image 4 shows how that looks in the original .mobi file.

There is no thing like `original mobi`. 
Any reader application renders an ebook in own original way. 
You may like or dislike it, but there is no a common standard.

![kybook-mobi-3](https://user-images.githubusercontent.com/791320/46330306-afdfce00-c655-11e8-8b80-c32bbe410848.png)

**Comment by kolyvan** [comment] 2018-10-02 05:17
Also for ebook I can't reproduce issue with drop-cap.

![kybook-ebook-1](https://user-images.githubusercontent.com/791320/46330430-43190380-c656-11e8-8169-9b303a5d2ac7.png)

**Comment by Mondyboy** [comment] 2018-10-02 05:44
Yes, going back to the default setting sorts out most of these problems.  I thought I’d done that, but clearly not.  Apologies.

There’s still the issue of the cover not being featured independently - that is without text under the cover.  I have set it to curl, but it seems the default is scroll and that may be why.

**Comment by kolyvan** [comment] 2018-10-03 06:36
Not a bug, closed.

**Closed as completed by kolyvan** 2018-10-03 06:36 UTC
Labels: wontfix
