### ISSUE TITLE
ePub missing titles & subtitles

### ISSUE THREAD

**Issue by camifran** [kolyvan/kybook#93] opened 2018-11-11 21:45 UTC
[Daniel.zip](https://github.com/kolyvan/kybook/files/2569681/Daniel.zip)

Hi, the enclosed epub displays wrongly in kybook, it doesn't show every heading and subheading. I enclose also a couple screenshots from another reader (marvin) for comparison. I've tried the default options as well as customized for the display. I own a 12.9 ipad pro 2nd gen.

Thank you in advance. 
![2018-11-11 22 44 02](https://user-images.githubusercontent.com/13048758/48318593-6777e080-e603-11e8-9499-320ec1559f8a.jpg)
![2018-11-11 22 44 22](https://user-images.githubusercontent.com/13048758/48318594-6c3c9480-e603-11e8-9685-b2db2f60e19d.jpg)

**Comment by kolyvan** [comment] 2018-11-12 05:18
Thank you much for the bug report.

The cause of issue is a wrong `hgroup` element style definition in a base epub stylesheet. 
Next release will include a fix for this issue.

Below the sample of page from your book with applied fix from the recent beta version.

![kybook-hgroup-fixed](https://user-images.githubusercontent.com/791320/48328084-1660fe80-e68e-11e8-997e-44e7b81e95d0.png)

**Comment by ghost** [comment] 2018-11-15 02:09
@kolyvan 
Small analog bug: 
File name saved in folder iCloud/kybook 3/ is not book title but random number combination, kybook can auto rename saved mobi filename according to its bookname：）

**Comment by kolyvan** [comment] 2018-11-20 03:16
fixed in v0.6.1

**Closed as completed by kolyvan** 2018-11-20 03:16 UTC
Labels: bug
