### ISSUE TITLE
BUG: Transparent images appearing with solid black backgrounds on pdf files

### ISSUE THREAD

**Issue by NineTailz13** [kolyvan/kybook#84] opened 2018-10-28 15:54 UTC
1. iPhone
2. iOS 12.0.1 
3. Kybook 3 v0.5.7 | #106
4. While I'm not 100% on this, it appears to happen with pdf files with large transparent images. 
5. For the transparency to render as clear and not black
6. The transparency turned black, blocking text and other graphs in the pdf

![black transparency in kybook 3](https://user-images.githubusercontent.com/44550430/47618333-11098e80-daa8-11e8-94f8-0b54c799d134.png)
![clear transparency on my computer](https://user-images.githubusercontent.com/44550430/47618344-2979a900-daa8-11e8-8426-9a11adf79919.png)

.

**Comment by kolyvan** [comment] 2018-10-29 02:49
Could you please share a sample pdf file (some link to download this pdf)?

**Comment by NineTailz13** [comment] 2018-10-29 14:38
[Here ya go!](https://the-eye.eu/public/Books/rpg.rem.uz/Dungeons%20%26%20Dragons/D%26D%205th%20Edition/Third%20party/Kobold%20Press/Tome%20of%20Beasts%20%28Big%29.pdf)

**Comment by kolyvan** [comment] 2018-10-30 03:18
@NineTailz13  Thank you very much for this pdf.
It seems I found the cause of this glitch, but I need first test heavily before releasing the fix.
Hope, in the 0.6.0 release this issue will fixed.

**Comment by NineTailz13** [comment] 2018-10-30 15:04
Thank you and good luck with fixing it!

**Comment by kolyvan** [comment] 2018-11-02 02:09
Fixed in v0.6.0

**Closed as completed by kolyvan** 2018-11-02 02:09 UTC
Labels: bug
